import React, { useEffect, useState } from 'react';
import { Alert, Button, Linking, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { auth } from '@/services/firebase/client';
import { continueAsMember, createAdmin, signInAdmin } from '@/services/firebase/auth';
import { createFamily, setSharing, watchLocations, watchMembers } from '@/services/firebase/families';
import { createInvitation, redeemInvitation } from '@/services/firebase/invitations';
import { currentVersion, checkLatestRelease, openRelease } from '@/services/updates/github';
import { startSharing, stopSharing } from '@/services/location/tracking';
import { useNetworkStatus } from '@/hooks/useNetworkStatus';
import { FamilyMap } from '@/features/map/FamilyMap';
import type { FamilyMember, MemberLocation } from '@/types/domain';

function AppContent() {
  // Convenience defaults for local setup only — editable, and meaningless until you tap
  // "Create Admin account" to actually register them as a real account in YOUR Firebase
  // project. They do not grant access to anyone else's family data or to this app in general;
  // Firebase Authentication still enforces a real account server-side.
  const online = useNetworkStatus(); const [uid, setUid] = useState<string>(); const [email, setEmail] = useState('admin@familysafety.local'); const [password, setPassword] = useState('Admin@123'); const [familyId, setFamilyId] = useState(''); const [familyName, setFamilyName] = useState(''); const [inviteCode, setInviteCode] = useState(''); const [displayName, setDisplayName] = useState(''); const [sharing, setSharingState] = useState(false); const [members, setMembers] = useState<FamilyMember[]>([]); const [locations, setLocations] = useState<MemberLocation[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => onAuthStateChanged(auth, user => setUid(user?.uid)), []);
  useEffect(() => { if (!familyId) return; const memberUnsubscribe = watchMembers(familyId, setMembers); const locationUnsubscribe = watchLocations(familyId, setLocations); return () => { memberUnsubscribe(); locationUnsubscribe(); }; }, [familyId]);
  // Clear session-scoped state on sign-out so the next person to use this device never sees a
  // previous account's family ID, members, or last-known locations.
  useEffect(() => { if (uid) return; setFamilyId(''); setFamilyName(''); setInviteCode(''); setDisplayName(''); setSharingState(false); setMembers([]); setLocations([]); }, [uid]);
  const ensureAuth = async () => { if (auth.currentUser) return auth.currentUser.uid; return (await continueAsMember()).user.uid; };
  const logOut = async () => { setBusy(true); try { await stopSharing(); await signOut(auth); setMessage(''); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to log out.'); } finally { setBusy(false); } };
  const create = async () => { setBusy(true); try { const id = await createFamily(await ensureAuth(), familyName.trim() || 'My Family'); setFamilyId(id); setMessage(`Family created. ID: ${id}`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to create family.'); } finally { setBusy(false); } };
  const invite = async () => { setBusy(true); try { if (!familyId) throw new Error('Create a family first.'); const result = await createInvitation(familyId); Alert.alert('Family invitation', `Share this one-time code with the member: ${result.code}`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to create invitation.'); } finally { setBusy(false); } };
  const join = async () => { setBusy(true); try { const id = await ensureAuth(); if (!familyId || !inviteCode || !displayName) throw new Error('Family ID, invitation code, and display name are required.'); await redeemInvitation(familyId, inviteCode, displayName); setMessage(`Joined family as ${displayName}.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to join family.'); } finally { setBusy(false); } };
  const toggleSharing = async (enabled: boolean) => { setBusy(true); try { const currentUid = await ensureAuth(); if (!familyId) throw new Error('Create or join a family first.'); if (enabled) await startSharing(familyId, currentUid); else await stopSharing(); await setSharing(familyId, currentUid, enabled); setSharingState(enabled); setMessage(enabled ? 'Location sharing is enabled.' : 'Location sharing is disabled.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to update location sharing.'); } finally { setBusy(false); } };
  const updates = async () => { setBusy(true); try { const release = await checkLatestRelease(); if (release) await openRelease(release.url); else setMessage('Update checking is not configured yet.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to check for updates.'); } finally { setBusy(false); } };
  if (!uid) return <SafeAreaView style={styles.container}><StatusBar style="auto" /><View style={styles.auth}><Text style={styles.title}>Family Safety</Text><Text style={styles.help}>Admins use a recoverable account. Members can join with a one-time invitation and anonymous device identity.</Text><Text style={styles.help}>First time on this Firebase project? Edit the fields below if you like, then tap "Create Admin account" once. Use "Sign in as Admin" every time after that.</Text><TextInput value={email} onChangeText={setEmail} placeholder="Admin email" autoCapitalize="none" keyboardType="email-address" style={styles.input} /><TextInput value={password} onChangeText={setPassword} placeholder="Password (6+ characters)" secureTextEntry style={styles.input} /><Button title="Sign in as Admin" onPress={async () => { try { await signInAdmin(email, password); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to sign in.'); } }} /><Button title="Create Admin account" onPress={async () => { try { await createAdmin(email, password); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to create account.'); } }} /><Button title="Continue as invited Member" onPress={async () => { try { await continueAsMember(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to connect.'); } }} /><Text style={styles.help}>{message}</Text></View></SafeAreaView>;
  return <SafeAreaView style={styles.container}><StatusBar style="auto" /><ScrollView contentContainerStyle={styles.content}><View style={styles.headerRow}><View style={styles.headerText}><Text style={styles.title}>Family Safety</Text><Text style={styles.subtitle}>{auth.currentUser?.email ?? 'Signed in as invited member'}</Text></View><Button title="Log Out" onPress={logOut} disabled={busy} /></View><Text style={styles.subtitle}>{online ? 'Online' : 'Offline — live updates paused until connected'}</Text><Text style={styles.heading}>Create or join a family</Text><TextInput value={familyName} onChangeText={setFamilyName} placeholder="New family name" style={styles.input} /><Button title="Create family" onPress={create} disabled={busy} /><TextInput value={familyId} onChangeText={setFamilyId} placeholder="Family ID" autoCapitalize="none" style={styles.input} /><TextInput value={inviteCode} onChangeText={setInviteCode} placeholder="Invitation code" autoCapitalize="characters" style={styles.input} /><TextInput value={displayName} onChangeText={setDisplayName} placeholder="Your display name" style={styles.input} /><Button title="Join with invitation" onPress={join} disabled={busy} />{familyId ? <Text style={styles.code}>Family ID: {familyId}</Text> : null}<Button title="Create one-time member invitation" onPress={invite} disabled={busy || !familyId} /><Text style={styles.heading}>Family map</Text><FamilyMap members={members} locations={locations} /><Text style={styles.help}>{members.length} authorized member(s), {locations.length} latest location(s).</Text><Text style={styles.heading}>Location sharing</Text><View style={styles.row}><Text style={styles.label}>{sharing ? 'Sharing enabled' : 'Sharing disabled'}</Text><Switch value={sharing} onValueChange={toggleSharing} disabled={busy} /></View><Text style={styles.help}>Sharing is visible and consent-based. Turn it off at any time. Android may ask for separate background permission.</Text><Text style={styles.heading}>Settings</Text><Text>App version: {currentVersion}</Text><Button title="Check for Updates" onPress={updates} disabled={busy} /><Button title="Project documentation" onPress={() => Linking.openURL('https://github.com')} /><Text style={styles.help}>{message}</Text></ScrollView></SafeAreaView>;
}

export default function App() {
  return <SafeAreaProvider><AppContent /></SafeAreaProvider>;
}

const styles = StyleSheet.create({ headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 }, headerText: { flex: 1 }, auth: { flex: 1, padding: 24, justifyContent: 'center', gap: 12 }, container: { flex: 1, backgroundColor: '#F8FAFC' }, content: { padding: 24, gap: 12 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 }, title: { fontSize: 30, fontWeight: '700', color: '#1E3A8A' }, subtitle: { color: '#475569' }, heading: { fontSize: 19, fontWeight: '700', marginTop: 20, color: '#0F172A' }, input: { backgroundColor: 'white', borderColor: '#CBD5E1', borderWidth: 1, borderRadius: 8, padding: 12 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: 'white', padding: 14, borderRadius: 8 }, label: { fontSize: 16 }, help: { color: '#475569', lineHeight: 20 }, code: { color: '#1D4ED8', fontFamily: 'monospace' } });
